### ISSUE TITLE
Does not catch m.file rather than m.image events

### ISSUE THREAD

**Issue by ajkessel** [ser/maubot-hateheif#1]
When a user posts HEIF images from the Element desktop app on Mac, msgtype is either always or sometimes m.file, not m.image. If you modify the script to also look for m.file, it works, although the content.info.width and .height are not populated. I fixed this with a hack:
```
@command.passive("", msgtypes=(MessageType.IMAGE,MessageType.FILE))
...
        if evt.content.msgtype != MessageType.IMAGE and evt.content.msgtype != MessageType.FILE:
            return
...
content.info.width=img_tst.size[0]
content.info.height=img_tst.size[1]
```
But I'm sure there is a better way to handle this.

**Comment by ser** [comment]
the problem is i do not have a macos device to develop and test anything :(

**Comment by ajkessel** [comment]
I submitted [a simple pull request](https://github.com/ser/maubot-hateheif/pull/2). Shouldn't be too controversial. I'm not sure why it's necessary to manually set the width/height as I do here -- maybe that's indicative of a different bug? But in any case the modified code is working well for me.

**Comment by ser** [comment]
I'm merging it without testing, but I might test in future if I have a mac available. Thanks!
